DirectoryPath: public
CheckDoctype: true
IgnoreAltMissing: false
IgnoreDirectoryMissingTrailingSlash: true
IgnoreDirs: [_print]
IgnoreEmptyHref: false
IgnoreInternalEmptyHash: true
IgnoreURLs:
- ^https?://localhost\b
- ^https://github\.com/bank-vaults/bank-vaults\.dev/commit/
- ^https://github\.com/orgs/bank-vaults/projects/
TestFilesConcurrently: false